### ISSUE TITLE
Como Professor, quero calcular a média, desvio-padrão, máximo e mínimo para o componente altimétrica,planimétrica e tridimensional para o dia, mês, estações do ano e ano todo sobre os arquivos selecionados.

### ISSUE THREAD

**Issue by tuliomt** [pel0ta/trabalho-grupo-2#13]
Descrição da história
Com os arquivos já formatados e feita a seleção da estação GNSS e período escolhido, o professor deseja realizar os cálculos de média, desvio-padrão, máximo e mínimo para o componente altimétrica, planimétrica e tridimensional sobre os arquivos selecionados. 
Critérios
 - [ ] Selecionar a estação GNSS.
 - [ ] Selecionar o período e/ou estação do ano.
 - [ ] Realizar todos os cálculos mencionados.

Tarefas
 - [ ] Realizar a implementação das funções para realização dos cálculos sobre a coluna os arquivos selecionados.
